name: lms-project
on: workflow_dispatch   # push --> Automatic trigger
jobs:
  Notification-Approval:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: send slack notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            channel: project-aug
            text: "LMS Prod deployment started approve it"
  database:
    needs: Notification-Approval
    runs-on: self-hosted
    steps:
      - name: create docker network
        run: docker network create lmsnetwork
      - name: create db-container
        run: docker container run -dt --name lmsdb -p 5432:5432 --network lmsnetwork -e POSTGRES_PASSWORD=admin123 postgres
    
        
